version: "3.8"
name: ansr-collins
services:
  adk:
    image: darpaansr.azurecr.io/adk:latest
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "./adk/mission_briefing:/mission_briefing"
      - "./adk/output:/output"
    command: "--mission_thread=manuever_thread --mission_class=area_search --restart" # Comment when using custom mission config
    # command: "--mission_thread=manuever_thread --mission_class=area_search --use_mission_briefing --restart" # Uncomment to use custom mission config
    ipc: host
    pid: host
    environment:
      - DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  deployment:
    image: ansr-collins
    ipc: host
    pid: host
    volumes:
      - "./adk/mission_briefing:/home/performer/dev_ws/src/mission_briefing"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]