absl-py==2.1.0
accelerate==0.29.2
argcomplete==1.8.1
attrs==21.2.0
beautifulsoup4==4.10.0
blinker==1.4
bloom==0.12.0
breezy==3.2.1
catkin-pkg==1.0.0
catkin-pkg-modules==1.0.0
cattrs==1.5.0
certifi==2020.6.20
chardet==4.0.0
clarabel==0.7.1
cloudpickle==3.0.0
colcon-argcomplete==0.3.3
colcon-bash==0.5.0
colcon-cd==0.2.1
colcon-cmake==0.2.28
colcon-common-extensions==0.3.0
colcon-core==0.16.1
colcon-defaults==0.2.8
colcon-devtools==0.3.0
colcon-installed-package-information==0.2.1
colcon-library-path==0.2.1
colcon-metadata==0.2.5
colcon-notification==0.3.0
colcon-output==0.2.13
colcon-override-check==0.0.1
colcon-package-information==0.4.0
colcon-package-selection==0.2.10
colcon-parallel-executor==0.3.0
colcon-pkg-config==0.1.0
colcon-powershell==0.4.0
colcon-python-setup-py==0.2.8
colcon-recursive-crawl==0.2.3
colcon-ros==0.4.1
colcon-test-result==0.3.8
colcon-zsh==0.5.0
configobj==5.0.6
contourpy==1.2.1
cov-core==1.15.0
coverage==6.2
cryptography==3.4.8
cvxpy==1.4.3
cycler==0.12.1
dbus-python==1.2.18
Deprecated==1.2.13
distlib==0.3.4
distro==1.7.0
distro-info==1.1+ubuntu0.2
docutils==0.17.1
dulwich==0.20.31
ecos==2.0.13
empy==3.3.4
Farama-Notifications==0.0.4
fastbencode==0.0.5
fastimport==0.9.14
filelock==3.13.4
flake8==4.0.1
fonttools==4.51.0
fsspec==2024.3.1
gpg==1.16.0
grpcio==1.48.2
gurobipy==11.0.0
gym==0.26.2
gym-minigrid==1.0.3
gym-notices==0.0.8
gym-unity==0.28.0
gymnasium==0.29.1
h5py==3.11.0
html5lib==1.1
httplib2==0.20.2
huggingface-hub==0.22.2
idna==3.3
importlib-metadata==4.6.4
iniconfig==1.1.1
jeepney==0.7.1
Jinja2==3.1.3
keyring==23.5.0
kiwisolver==1.4.5
lark==1.1.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lxml==4.8.0
Markdown==3.6
MarkupSafe==2.1.5
matplotlib==3.7.3
mccabe==0.6.1
mercurial==6.1.1
mlagents==1.0.0
mlagents-envs==1.0.0
more-itertools==8.10.0
mpmath==1.3.0
netifaces==0.11.0
networkx==3.3
nose==1.3.7
nose2==0.9.2
notify2==0.3
numpy==1.22.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.0
olefile==0.46
onnx==1.12.0
opencv-python==4.9.0.80
osqp==0.6.5
packaging==21.3
pandas==2.2.2
patiencediff==0.2.1
PettingZoo==1.15.0
Pillow==9.0.1
pluggy==0.13.0
protobuf==3.19.6
psutil==5.9.0
py==1.10.0
pybind11==2.12.0
pycairo==1.20.1
pycodestyle==2.8.0
pydocstyle==6.1.1
pyflakes==2.4.0
PyGithub==1.55
Pygments==2.11.2
PyGObject==3.42.1
PyJWT==2.3.0
PyNaCl==1.5.0
pyparsing==2.4.7
pytest==6.2.5
pytest-cov==3.0.0
python-apt==2.4.0+ubuntu3
python-dateutil==2.9.0.post0
python-gitlab==2.10.1
pytz==2024.1
PyYAML==5.4.1
qdldl==0.1.7.post1
regex==2024.4.16
requests==2.25.1
requests-toolbelt==0.9.1
roman==3.3
rosdep==0.22.2
rosdep-modules==0.22.2
rosdistro==0.9.0
rosdistro-modules==0.9.0
rospkg-modules==1.5.0
safetensors==0.4.3
scipy==1.11.4
scs==3.2.4.post1
SecretStorage==3.3.1
shapely==2.0.4
Shimmy==1.3.0
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.3.1
stable_baselines3==2.3.0
sympy==1.12
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tikzplotlib==0.10.1
tokenizers==0.15.2
toml==0.10.2
torch==2.1.0
torchvision==0.17.2
tqdm==4.66.2
transformers==4.39.3
transforms3d==0.4.1
triton==2.1.0
typing_extensions==4.11.0
tzdata==2024.1
unattended-upgrades==0.1
urllib3==1.26.5
vcstool==0.3.0
vcstools==0.1.42
wadllib==1.3.6
webcolors==1.13
webencodings==0.5.1
Werkzeug==3.0.2
wrapt==1.13.3
zipp==1.0.0
